project:
  type: website
  output-dir: docs

website:
  title: "Aviv Nur"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd

format:
  html:
    theme:
      light: united
      dark: solar
    css: styles.css
    toc: true
    page-layout: full


